### ISSUE TITLE
Error with owner_set_params

### ISSUE THREAD

**Issue by lormayna** [nneonneo/ffsend#12]
Hello, I am trying to use ffsend inside a python script. This is the error that I got when I am trying to modify params:

In [40]: ff = ffsend.FFSend('https://send.firefox.com/')                                                                                                               

In [41]: service, fid, secret = ffsend.parse_url('https://send.firefox.com/download/XXXXXX/#TTTTTTTT')                                         

In [42]: print(params)                                                                                                                                                 
{'dlimit': 3, 'ttl': 60000}

In [43]: ff.owner_set_params(fid, 'CCCCCCCCC', params)                                                                                                      
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-43-27ebbdc61e1b> in <module>
----> 1 ff.owner_set_params(fid, 'CCCCCCCCCC', params)

~/progetti/alloggiati/lib/python3.5/site-packages/ffsend.py in owner_set_params(self, fid, owner_token, new_params)
    405         '''
    406         resp = self.api.post_params(fid, owner_token, new_params)
--> 407         resp.raise_for_status()
    408 
    409 def single_file_metadata(filename, filesize, mimetype='application/octet-stream'):

~/progetti/alloggiati/lib/python3.5/site-packages/requests/models.py in raise_for_status(self)
    938 
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 
    942     def close(self):

HTTPError: 400 Client Error: Bad Request for url: https://send.firefox.com/api/params/QQQQQQQ

I just masked all the sensible parameters.

**Comment by nneonneo** [comment]
Unfortunately send.firefox.com does not allow you to set the download limit greater than 1 if the file was uploaded anonymously (and currently ffsend doesn't support Firefox accounts because the authentication flow appears to require a browser). If you use `'dlimit': 1` it will work, but it may not be what you wanted.

(Firefox Send used to support a higher limit for anonymous users, and I hope they'll bring that feature back, so I won't drop support for it in the API).
