### ISSUE TITLE
Packing up and publishing on PYPI

### ISSUE THREAD

**Issue by zdog234** [nneonneo/ffsend#5]
Hello! Thanks for creating this package. I think it could be really cool to package this up a bit and publish it on PYPI.

**Comment by zdog234** [comment]
I'd be up for submitting a PR to do some of this.

**Comment by nneonneo** [comment]
If you want to add the necessary bits for publishing to PyPI, by all means! I can publish the package itself since I have done so for other packages in the past.

**Comment by nneonneo** [comment]
Closed via #10 - now published at https://pypi.org/project/ffsend/.
