### ISSUE TITLE
Error downloading file

### ISSUE THREAD

**Issue by KTibow** [nneonneo/ffsend#7]
I've been using ffsend with Python 3 lately. When I try to download a file, I get this:

```python3
Traceback (most recent call last):
  File "ffsend.py", line 374, in <module>
    exit(main(sys.argv[1:]))
  File "ffsend.py", line 329, in main
    service, fid, secret = parse_url(args.target)
  File "ffsend.py", line 71, in parse_url
    return service, fid, secret
UnboundLocalError: local variable 'service' referenced before assignment
```
Does anybody know the source of this?
Reminder: Python 2 is now phasing out.

**Comment by KTibow** [comment]
Is it because of the upgraded protocol?

**Comment by nneonneo** [comment]
Should be fixed by 50567c9.

**Comment by nneonneo** [comment]
Ok, hopefully *now* it's fixed - or at least it throws a better error message! If it fails, you should post a test URL to show what's failing.

**Comment by KTibow** [comment]
Thanks!
