### ISSUE TITLE
Library readiness

### ISSUE THREAD

**Issue by KTibow** [nneonneo/ffsend#8]
This is a great project! Does anybody know how to use this with another piece of code?
I was thinking of making a Python script that uploads to Firefox Send, and then makes a QR code from that.
I may or may not be able to solve this on my own, but things go faster with more people. Thanks!

**Comment by nneonneo** [comment]
The most recent update introduced an `FFSend` class which provides a "mid-level" API for Firefox Send. This simplifies uploading a lot; now you just do the following:

    send = FFSend('https://send.firefox.com/')
    metadata = single_file_metadata(filename, filesize)
    res, secret = send.upload(metadata, fileobj)
    print(res['url'], res['owner'])

where `filename` is the filename, `filesize` is the size of the file in bytes, and `fileobj` is the open file object to upload, *in binary mode* (e.g. `fileobj = open(filename, 'rb')`). That should be all you need.

**Comment by nneonneo** [comment]
Happy to take concrete suggestions on how to make that interface even simpler. (The "mid-level" API is intended to still be quite close to what Send uses internally, but with all the crypto stuff taken care of. I'm still planning a high-level API which would be even simpler to use.)

**Comment by KTibow** [comment]
I think it’s simple enough, though. You should consider adding this to the README!
Also, for the README, try out adding color: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

Thanks! This was very helpful.
